apiVersion: v1
kind: Namespace
metadata:
  name: pgstay

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd

---
apiVersion: v1
kind: middleware
metadata:
  name: middleware
  labels:
    name: middleware

