apiVersion: v1
kind: Secret
metadata:
    name: grafana-secrets
    namespace: grafana
type: Opaque
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:QrKSBtKVyln1fbQU9tO7v6hxWgU=,iv:l87o+Xk+XtnCyJN/OMPWsVk4wQTloN8fEtkmATNYwDc=,tag:GDvu4FvYxUr5JsVNsY4j1g==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:dZYehr2L4nnn6GTGg18RrWTIm5rHYEkJxJQ3CKT+a66zIwwrrFk71Q==,iv:oM51iF5tZ8oUKlA03G6aj+Et6+uBYprq7eZeZPJSEf8=,tag:PK1elb4yDpz6+c9cBGju/g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTDNTZUVuSm9aVG55VGJa
            eUg0blY0Qmx0VENJNUhPVW4zTGY0TXpONzFFCjFNRHloWThOQTMwL0M2aGNMS3V6
            azdBdjA0alM2OWZoV2xPQVo3dUhWNVEKLS0tIGZsd1c3WmhiQTRLbkJsMythQXMy
            UWxaR1lTdmhpSzhicDdlNm9HZnpFUkUKmdxRpZYbWeAAFosY1zc3VRQ01gDnLOm0
            6uz8ysugtfkeipzUXKi32stroQOz3NFhOAOTrdN5kwhmwnqQcXS71Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f8n32ugy56xu6gjwzcxq809sq5x8gdnf56nas8ral33eg956we0smjq47u
    encrypted_regex: ^(data|stringData|appSecrets)$
    lastmodified: "2026-09-10T12:22:58Z"
    mac: ENC[AES256_GCM,data:0VrT4VZm51bnFy1TQ77zJclEQOq33u26zyFnXft8nY26tqyGzVNQKbdMyvHarFJc+6XPJDSnRYyt21RNx+gr5TBfVWpsN9bVRxSd/yF580r7WuqtlYPdxhIaAwr96qXKxnzQsF3i6p6+dCfuxXFgMSoeC9GycYZPA6UaEv7trJ4=,iv:3XaPYdD8K0pmq5y9swM52M3QuWn6aZ+fVO9o8fPv7g8=,tag:Nu7d3v00FPGj+EYiF1FsRw==,type:str]
    version: 3.13.3
