mode: daemonset

image:
  repository: otel/opentelemetry-collector-contrib
  tag: "0.92.0"

presets:
  logsCollection:
    enabled: true
  kubernetesAttributes:
    enabled: true

config:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

    k8sobjects:
      objects:
        - name: events
          mode: watch

  processors:
    memory_limiter:
      check_interval: 1s
      limit_mib: 1000
      spike_limit_mib: 200

    transform:
      log_statements:
        - context: log
          statements:
            - set(severity_text, "INFO") where severity_text == ""
            - set(attributes["level"], severity_text)

    batch:
      timeout: 1s
      send_batch_size: 1000
      send_batch_max_size: 1500

  exporters:
    otlphttp:
      endpoint: "http://loki.grafana.svc.cluster.local:3100/otlp"
      tls:
        insecure: true

    debug:
      verbosity: basic

  service:
    pipelines:
      logs:
        receivers:
          - otlp
          - filelog        
          - k8sobjects
        processors:
          - memory_limiter
          - k8sattributes  
          - transform
          - batch
        exporters:
          - otlphttp
          - debug