apiVersion: ENC[AES256_GCM,data:yzc=,iv:zcOb+EHq3taZnc+Fcsq4EGh5dzp8+nY0t80hn8Y02QI=,tag:MFQypTTXadZWj419GSt2CA==,type:str]
kind: ENC[AES256_GCM,data:z92jYISS,iv:3EQujz9PAIHgITQzSxyaO4QKxGz8cHSuOpUD5S5GnFI=,tag:RHEguOc1AB8uz4LjS7hO9g==,type:str]
metadata:
    name: ENC[AES256_GCM,data:hLUvmtDK8dYSPsw4WpiRqk6q,iv:vdjaNLi090Gj5nVYTwuCqOMFiIvtGJ7U5CrAkr8NGUM=,tag:ZT6zUXGCotjV5YgRqVAJOw==,type:str]
    namespace: ENC[AES256_GCM,data:iKSvYPks,iv:D/crnM9tqzm8i9g5D7zwkqM1Cw81NNQLd8ZFgjiH3ko=,tag:18PHNILPhmWB8GeuRQrDyg==,type:str]
type: ENC[AES256_GCM,data:8sPxacru,iv:LAJeb9jKfCtg3YnF0Wo7rbdWSXBlmbm9ZdItuRZMYbc=,tag:qRRiucOaOeU9JwUZHLbtiA==,type:str]
stringData:
    MONGODB_STRING: ENC[AES256_GCM,data:Vk6yUOBFmjNKB7rb0ZemexAsKVBeded/GrBtgbHGy5UCUqGInA53yuNRuH++rnU4ee7cH0nEktUZ6gIXvx5nPQ296w==,iv:hXfBUd5zrXc1QzNCoeUfuNwqPAuFASnnvybp9d+bEQ8=,tag:BiJr1AjYhY5nBCukGnKeTA==,type:str]
    DB_NAME: ENC[AES256_GCM,data:theW3XqzMZpXss8=,iv:7/gVgQV2MA/0Ys6CSUkS2pnmsETtuhon/BTiS2TVZ3Q=,tag:MYZBnBhnu2P3h5ccD2DoNw==,type:str]
    CLOUFINARY_NAME: ENC[AES256_GCM,data:Xz1HRFWkl33V,iv:ZzvlA1sfsZeVeFJUCmDUJuOkm4EYvwELqzw6m93WPuw=,tag:vbfDXzIVEznj4tnsxcCw7A==,type:str]
    CLOUFINARY_API_KEY: ENC[AES256_GCM,data:k0k9djfB+e+qfj4ZMiD2,iv:6zGYM1EXAEnccyvgGY2IgYG9cuNGjkLmzybEbGHy5kU=,tag:/5ZWz0cmYisVHdnWNu6sPA==,type:int]
    CLOUFINARY_SECRET_KEY: ENC[AES256_GCM,data:Rm+sllLz6hl691o4NbcDSbzbsgDfrgOaZdif,iv:aZvvCgO4mpAPyzHfGdcuXeAFaTdu5ty9e77D7C40zPs=,tag:schBvvSEtOUfUCYdQrDmng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ0Jaak1XaG9MbTVWbHEy
            TUlQWkRlWUF4UUM4UzZ1ZGJnd2tMOXp2ekZ3CnlvM3ltZUw3c0ZZZmJwa1cwUm0w
            c2E0TFR5ck9qUjNLRG9VcHdmWFpoZUkKLS0tIHUyMUhhRmIwM0JiVElHTXFHV2ls
            eDZYVThhN0p1Sk0xRW9sZVlEcCtBQ3cK9TamGy0VDAStFISQWsCDuElXswDmVoaU
            ImVgOpF/RzoWuh+K6pI+oWrazosmwkG1ZWbmEXLWmrzNSqvjW0CZ1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f8n32ugy56xu6gjwzcxq809sq5x8gdnf56nas8ral33eg956we0smjq47u
    lastmodified: "2026-07-30T14:10:21Z"
    mac: ENC[AES256_GCM,data:dxNVHwerJ3s1hd4BlUAhLmcU4q1MVsgYJnBeB0mLhMeFwdkKnZ82EgANI2GvBOu0UTPEP+Vmk7oYDaMA6EfPLziOv8KB0hqrJf0fKDqkXWHcgCZJ/A5+s2sJJvsFKCNHjXfuyV2k5QBISC4Qc7H2e3n7MWr108JvnREvGtEqaaU=,iv:lqoS5b+/Dn53vUk9/ma1j/m9I8j+5BFn8k5sb5KAmAI=,tag:BDGCr9Z2UBMf6ShlMasRtA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
