apiVersion: v1
kind: Secret
metadata:
  name: roomService-secret
  namespace: pgstay

type: Opaque

stringData:
  MONGODB_STRING: "mongodb+srv://RoomService:RoomService@cluster0.4fkgrvc.mongodb.net/"
  DB_NAME: RoomService
  CLOUFINARY_NAME: dfhramgf6
  CLOUFINARY_API_KEY: 693559376189182
  CLOUFINARY_SECRET_KEY: Ph1bBmHpDqCwa_R-la_1ewopykQ