apiVersion: v2
name: application-chart
description: "Universal base Helm chart for all projects"
type: application

version: 1.2.0

appVersion: "v1.0.4"

maintainers:
  - name: Tanmay Shirbhayye
    email: tanmayshirbhayye60@gmail.com