apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName | default (printf "%s-secret" .Release.Name) }}
  labels:
    app: {{ .Release.Name }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.appSecrets }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}