apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.service.name | default .Values.appName | default .Release.Name }}

  labels:
    {{- include "k3s-apps.labels" . | nindent 4 }}

spec:
  type: {{ .Values.service.type | default "ClusterIP" }}

  ports:
    - name: {{ .Values.service.portName | default "http" }}
      protocol: {{ .Values.service.protocol | default "TCP" }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}

  selector:
    {{- include "k3s-apps.selectorLabels" . | nindent 4 }}
