apiVersion: v2
name: k3s-apps-chart
description: A reusable Helm chart for deploying applications on a K3s cluster
type: application

version: 0.1.3
appVersion: "1.0.0"

maintainers:
  - name: Tanmay Shirbhayye
    email: tanmayshirbhayye60@gmail.com

keywords:
  - kubernetes
  - k3s
  - helm
  - applications
  - gitops

home: https://github.com/Tanmay-008/k3s-cluster
sources:
  - https://github.com/Tanmay-008/k3s-cluster