apiVersion: v1
kind: Secret
metadata:
    name: roomservice-secret
    namespace: pgstay
type: Opaque
stringData:
    MONGODB_STRING: ENC[AES256_GCM,data:ktGxkLwNtsKzx8do7zMVVLgEg7HYqq+bjnXfPmvb6wNQuyyXZvBDzQc1DhGZ3txdezOpaWRyRYSgt9T2wDer5rtm2w==,iv:KgiCIIF+geaDiHfnL0dLcKFiIgmyuVbq2IUdXKF+Pio=,tag:5WdrZJN9LWZXF7f0oAV5pg==,type:str]
    DB_NAME: ENC[AES256_GCM,data:rGoiWORKgn5ne9Y=,iv:dEG10TojA1gyJ22ro40Iv7UVKc/A6dHEhI0iXp58pSg=,tag:PHLdWlGO7258lu6yVXOefQ==,type:str]
    CLOUFINARY_NAME: ENC[AES256_GCM,data:JUuPNo1G4ys8,iv:bW6YT44hjv69FotgIBuzXkWXZ+5QoxsW7QzQEnGzPRg=,tag:sa1jTJg3hTTVgI1BVwfWLA==,type:str]
    CLOUFINARY_API_KEY: ENC[AES256_GCM,data:8v3x3xdgKE9CyR3ToR96,iv:0FiTfl/yQYrPqhWWpuSKhhzgObQ5znauWkydE8VirOQ=,tag:JXSBSsUILEWc+K4SUD00YA==,type:int]
    CLOUFINARY_SECRET_KEY: ENC[AES256_GCM,data:0BOMXzB1bjCFNIo0PGMAcijq2poTUnkMFXuY,iv:dls+rRtEsPUJwlV7B3iVHVjjAUK178GKI7muZ2pzbkA=,tag:CO0pWCKKocmk84dcn8QXPw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKamxleGQwMEoxSWNDdEth
            VFIxUUhwV2g4bGFSaHJKWFRTMUlrMXlYanlJClFmVDEvOEVuWDdnYmJjUEtsMXVS
            cXlsTFF3cFZiSHVQSkN0R2tPWTBHZFUKLS0tIFYvV095Y2FiUmtja1M1U0R1VWxF
            UU5XMUVRMmNEQW9NdHEvMGgrODNuMFUKqdhwBAFyA19hnG0wOrrUcwFWnYjV1MJW
            gNo4lOqpCDKvpOilZeOAK8H6GpEsBMgKX7c7NUXI9KKo6mXmbLpreQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f8n32ugy56xu6gjwzcxq809sq5x8gdnf56nas8ral33eg956we0smjq47u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-11T11:57:01Z"
    mac: ENC[AES256_GCM,data:dp9Y+/Ocm+lcYXIsJTMhnJ827S3u3QRB/6ZwIDxGCLPnsR/dlUyFm/KxYZuvS94R4W+vb+pF+oU1bYFA23j9E9UkzR6ExMnF8CuXQCSDOqzZHnc4y0L0285tQ/qjd4WK943AcRA3KETarP0SaL7tcDcFCiG4sJoyJ8Ln2R+gAUs=,iv:nu4WrrCB9kRQ+R15gFDv8bdzQWCzv83a4hIak75U8oE=,tag:MH33P9+897mrU5UdYxSLUQ==,type:str]
    version: 3.13.3
