apiVersion: v1
kind: Secret
metadata:
    name: roomservice-secret
    namespace: pgstay
type: Opaque
stringData:
    MONGODB_STRING: ENC[AES256_GCM,data:7WMfvoRKk3CLOKiwsZYK7lZ3tgsVmkdOEKW2cD//jGyiMBkhTtyaiVKl7uvCj0oj/liGhojdAbX1ZaL8cHWnTfiVRQ==,iv:S3uupYiXo37+iv7ahEStdHyF/LoFvex8N9PNxJCzArg=,tag:3Qwwi9CRJLv7+jYbMB4kpQ==,type:str]
    DB_NAME: ENC[AES256_GCM,data:XrL7jazMuTQB3YY=,iv:qNlilamzg4BHKBMGoZ+7PAOBK9FJiXtdZuUG0+2Jbwk=,tag:QWVEdLkAg8nP+lNaBPApZA==,type:str]
    CLOUDINARY_NAME: ENC[AES256_GCM,data:WbdFJz35rdfO,iv:MdPG9IzQTgUlPNiNXhhWfW+mNHf9iu+mNxa5XzLStj0=,tag:cLxmklZGsYWZ5QxBqHhX3g==,type:str]
    CLOUDINARY_API_KEY: ENC[AES256_GCM,data:iwOsPWpoFLi6eee0CaDv,iv:YTAfe6BxJE8gfMuRXSnJA0L6djEXM4o8slLc3K85mVk=,tag:LiAykNtmlR7bLfnLF4MEWA==,type:str]
    CLOUDINARY_SECRET_KEY: ENC[AES256_GCM,data:eoEaO/OYE4R6X4QC9vgfNKWznGw28dAOJEcx,iv:jGw5ZT18bdTwPhlbNq9+FKdL5UpqdwVjRst112ofz8w=,tag:hBjnW8zQDuh4OLAuHhp7eg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCN0VaTHduUklpYmU4SytP
            RTBkSE5ySVdNZHVzU3k0cDhZK096dXNqbGdZCldYdmI3bTFGUUxzQ1NIcDA3Zkk2
            ZGlxYXZsbFlSQlhnQUVvYnFXQ3I3MFUKLS0tIG1XTzlzdWd3M3o0cHkxZktsRktK
            bk5OS1VyMTBLcFlDODNpLy9vQnZYY1UKluCTKqCKSTUqWkrX3nriRH8nLmdv6RF/
            a2WvPo9LOX+wtyZ4Dr80SxFOwg7pjJLE42K6kWGnKO9OU8zy6LRzKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f8n32ugy56xu6gjwzcxq809sq5x8gdnf56nas8ral33eg956we0smjq47u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T13:03:04Z"
    mac: ENC[AES256_GCM,data:ytcLwJA2jlskuqDcp/D3v4GHw+5XuC3f8EUkeDBqteV5KRg4yfauy0/huQRA7Y2HKG+zrYo5PYdUgtukMsD5NzPmOcFgWnygh82hqNAtj9atbl08IZNEqrP7Z0v/rEsJMnekMcMw8QJE5bRIYxmFs18Er3h1Kmfc4eqsVONKBOo=,iv:QYP9noDhR9yxfFRuZETrrTzi8zpI4/7IudSLy227cHM=,tag:cBSzvwoGgidKZcvT7BQGRQ==,type:str]
    version: 3.13.3
