apiVersion: v1
kind: Secret
metadata:
    name: roomservice-secret
    namespace: pgstay
type: Opaque
stringData:
    MONGODB_STRING: ENC[AES256_GCM,data:EL+tmbk/o/yXAEOzJPSYOcAkYGb/VTTL8Ae9Wmpp+9thJLBLeJZpI+0fimd1gbTSvZAvhZBX15eL2f8eeghGsRGJUw==,iv:aIogJOUDU7IyxZKnAGxzEAMf+T7fo5x1ilwO+BV1ckk=,tag:MMAL6Ygd9+neazDQyYiZ8Q==,type:str]
    DB_NAME: ENC[AES256_GCM,data:PfMfrw3noVJIb/w=,iv:icIbzKARnZ/ZTtu79mOQpakrgCv4hfIyBzmdZJsi804=,tag:4e2KLj+dF7/5mm0GkZe5Gw==,type:str]
    CLOUFINARY_NAME: ENC[AES256_GCM,data:yNSGcFynjwV/,iv:UiVWkZuRniL85RrpHLC3Z0RdGFtUpE4mYFz6vr8TkG8=,tag:Jw89f6uIONQLgx5ncotBig==,type:str]
    CLOUFINARY_API_KEY: ENC[AES256_GCM,data:o//SoKcFfyVEqKqVfEcZ,iv:91bmoZXhWNx2vrbAHLlQAkIc2+JEcFwEb4QpJgg7MUU=,tag:CMh6SuHbx38fsfNh58uTnA==,type:int]
    CLOUFINARY_SECRET_KEY: ENC[AES256_GCM,data:CzOD5basU22QO6Jbs+AB9JU6QQr+YIJ364BL,iv:2Kyz74Pofe671PzH21ZmelOc2VrV4NFWVq/tdBfOQ8U=,tag:Nr3sclB1NEMTmNGygPiovg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOTXJvVUdiS2VsajJxcmNE
            ekhzY3NVNHoyOEJzMmJOKzBlckE0UnNKYUE0Ck5HS0dnUGpqRW1aVENTRWZZbXF4
            TjFVTFBtVWdROVdIQzJFNVZEaEJLTTAKLS0tIHRaVUNzbDB4ZEd3UDN0VFNsNWI1
            WFY2d3VKekFXQm90ZTFDRGZCazRveWcKGxnEawFsUJMW7sk5LrCaPFePQ5PPI6ap
            Oh3FNukSiA9nMJJlXtqWL2AYbLoGuS25K4Xzlvo8tFwJQXpOz2x5Kg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1f8n32ugy56xu6gjwzcxq809sq5x8gdnf56nas8ral33eg956we0smjq47u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T12:34:45Z"
    mac: ENC[AES256_GCM,data:d7HJxP7ljBQmMBT+MqH/qq4EU8PK3oinULmIHSsICY/RpnBqWBbn/+DSR4dRuzyjM/x4/ol7LdEwGjCBrbPD55Cq4Q7iKxrINM6+4kjsJdGivXoT/QH6NeP19myI2C4Z8OCLyrUCLVxCDghZapNh4xQ5TW4FMP7QuNQYYkefYrc=,iv:gln7aIErD/yvMcguLUIiK81FUTF8VEy39XJaVczzgJ8=,tag:Ansr3+GAfEEpKsknRo/3QQ==,type:str]
    version: 3.13.3
