k3s-apps-chart:
  replicaCount: 1
  image:
    repository: tanmay678/room-service
    tag: latest
  service:
    port: 80
  targetPort: 5000

  healthCheck:
    enabled: false

  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi

  secrets:
    enabled: true