replicaCount: 1

image:
  repository: tanmay678/room-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

healthCheck:
  enabled: false
  path: /health
  initialDelaySeconds: 10
  periodSeconds: 10
  readinessInitialDelaySeconds: 5
  readinessPeriodSeconds: 10

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi