apiVersion: cert-manager.io/v1
kind: Certificate

metadata:
  name: tanmayshirbhayye-tech-wildcard
  namespace: YOUR_NAMESPACE

spec:
  secretName: tanmayshirbhayye-tech-tls

  privateKey:
    rotationPolicy: Always

  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

  dnsNames:
    - tanmayshirbhayye.tech
    - "*.tanmayshirbhayye.tech"